### PR TITLE
VBF optimization

### PR DESCRIPTION
**Pull request by rkansal47**
- [x] Using MC backgrounds for ABCD scan
 - [x] Save args used for creating templates 
 - [x] Re-do VBF scan
 - [x] Check limit on VBF signal
 - [x] Check combined limit (`24May13VBF` templates)
 - [x] Check limit if prioritizing Cat 1 > VBF (`24May13VBFPriorityCat1` templates)

### CODE REVIEW

**Comment by cmantill** [comment]
What does ` Using MC backgrounds for ABCD scan` mean? Weren't we already doing that?

**Comment by rkansal47** [comment]
@cmantill They were not being loaded in the PostProcess.py script before for the scan.

**Comment by cmantill** [comment]
@rkansal47 one last question. This line is currently:
```
mass_window = np.array(window_by_mass[args.mass])  # + np.array([-5, 5])
```

Is there a motivation to shift it by 5? what should we keep?

**Comment by rkansal47** [comment]
@cmantill It was being increased by 5 GeV on each side, so 105 - 145 GeV but it's not anymore... I'm not sure what the motivation was previously to increase it. I think it makes more sense for it to match the signal window we blind.

**Pull request merged**
